#!/usr/bin/env bash

args=$@

git submodule init
git submodule update

flags="--verbose=1 -t $HOME"

if [[ "$args" == "--uninstall" ]]; then
  echo 'Uninstalling'
  flags="-D --verbose=1 -t $HOME"
fi

stow $flags ag
stow $flags asdf
stow $flags bin
stow $flags ctags
stow $flags git
stow $flags ruby_config
stow $flags shells
stow $flags tmux
stow $flags vim
stow $flags zshell
stow $flags neovim
stow $flags alacritty

# install oh-my-zsh
# curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh

# app.github_clone('chriskempson/base16-shell', "#{app.home}/.config/base16-shell")
