#!/usr/bin/env bash

args=$@

git submodule init
git submodule update

flags="--verbose=1 -t $HOME"

if [[ "$args" == "--uninstall" ]]; then
	echo 'Uninstalling'
	flags="-D --verbose=1 -t $HOME"
fi

stow $flags tmux
stow $flags zshell
stow $flags shells --adopt

# stow $flags i3
# stow $flags ag
# # stow $flags asdf # TODO: This is messed up after the last update
# stow $flags bin
# stow $flags ctags
# stow $flags git
# stow $flags ruby_config
# stow $flags shells
# stow $flags tmux
# # stow $flags vim
# stow $flags bash
# stow $flags alacritty
# stow $flags kitty
# stow $flags base16-shell
# stow $flags osx-desktop

# neovim config was moved to mjacobus/nvim
# stow $flags neovim # older
# stow $flags nvim   # newer
