#!/usr/bin/env bash

# so I can start puma on port 80
allow-all-ports

# node watch stuff - not sure this is working atm
sudo sysctl fs.inotify.max_user_watches=999524288

# Start google drive
google-drive-ocamlfuse ~/GoogleDrive

start-ssh-agent
