source ~/.vimrc

" Workaround for the system clipboard
" https://github.com/neovim/neovim/issues/583
function! ClipboardYank()
  call system('xclip -i -selection clipboard', @@)
endfunction
function! ClipboardPaste()
  let @@ = system('xclip -o -selection clipboard')
endfunction

vnoremap <silent> y y:call ClipboardYank()<cr>
vnoremap <silent> d d:call ClipboardYank()<cr>
nnoremap <silent> p :call ClipboardPaste()<cr>p

set termguicolors
" colorscheme base16-tomorrow-night
" colorscheme jellybeans
colorscheme lucius

" function! ClearEchoAndExecute(command)
"   execute ":terminal clear && echo '" . a:command . "' && " . a:command
" endfunction
"
" let test#strategy = "neovim"
"
" function! test#strategy#neovim(cmd) abort
"   " botright new
"   call ClearEchoAndExecute(a:cmd)
"   " call :termopen(a:cmd)
"   " au BufDelete <buffer> wincmd p " switch back to last window
"   " startinsert
" endfunction
" let test#strategy = "dispatch"
