#!/usr/bin/env sh

# https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
# Installing
# - brew install koekeishiya/formulae/yabai
# - sudo yabai --install-sa
# - yabai --start-service
# echo "$(whoami) ALL=(root) NOPASSWD: sha256:$(shasum -a 256 $(which yabai) | cut -d " " -f 1) $(which yabai) --load-sa" | sudo tee /private/etc/sudoers.d/yabai

yabai -m config layout                bsp
yabai -m config auto_balance          on
yabai -m config window_placement      second_child
yabai -m config split_ratio           0.50
yabai -m config top_padding           0
yabai -m config bottom_padding        0
yabai -m config left_padding          0
yabai -m config right_padding         0
yabai -m config window_gap            0

yabai -m config active_window_opacity 0.95
yabai -m config normal_window_opacity 0.90
