#!/usr/bin/env bash

target=tags-php
bin=~/.dotfiles/bin/phpctags.phar

echo "Using $bin to generate $target"

php $bin --languages=php \
  --langmap=php:.inc.php \
  --file-scope=no \
  -R -f tags-php .
