#!/usr/bin/env ruby

require File.expand_path('../../ruby/lib/dev/cli/application', __FILE__)
require File.expand_path('../../ruby/lib/dev/cli/command/base', __FILE__)
require File.expand_path('../../ruby/lib/dev/cli/command/docker_mysql', __FILE__)
require File.expand_path('../../ruby/lib/dev/cli/command/git_checkout_branch', __FILE__)

commands = [
  Dev::Cli::Command::DockerMysql.new,
  Dev::Cli::Command::GitCheckoutBranch.new
]

application = Dev::Cli::Application.new
application.append_commands(commands)
application.start(ARGV)
