#!/usr/bin/env bash

# https://github.com/github/ghcs

set -e

DOTFILES="$HOME/.dotfiles"

[[ ! -d ~/Projects ]] && ln -s /workspaces ~/Projects

if [[ ! -d ~/Projects/github-projects ]] ; then
  mkdir -p ~/Projects/github-projects
  ln -s ~/Projects/github ~/Projects/github-projects/github
fi

command -v tmux || sudo apt-get install -y tmux
command -v stow || sudo apt-get install -y stow
command -v tig || sudo apt-get install -y tig
command -v ag || sudo apt-get install -y silversearcher-ag

command -v brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
command -v gh || brew install gh
command -v nvim || brew install nvim --HEAD

git clone $GH_CONFIG_REPO ~/.github-config

asdf install python
pip install neovim

sudo chsh -s $(which zsh)

 # Use RDM for copy/paste and open support
wget https://github.com/BlakeWilliams/remote-development-manager/releases/download/v0.0.3/rdm-linux-amd64
sudo mv rdm-linux-amd64 /usr/bin/local/rdm
chmod +x /usr/bin/local/rdm

gh config set browser "rdm open"
