#!/usr/bin/env bash

# ------------------------------------------------------------------
# This command is meant to be run manually once the CS is spinned up
# Because I was not able to automate it yet in script/codespaces-post-start.
# The brew installation script requires some user interactions and I did not know
# how to bypass it
# ------------------------------------------------------------------

set -e

command -v brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
command -v nvim || brew install nvim --HEAD
