#!/usr/bin/env bash

# https://github.com/github/ghcs

set -e

MAIN_PROJECT=`pwd`

function log() {
  message="`date` - $1"
  echo $message
  echo $message >> ~/DOTFILES_LOG
}

function start_log() {
  log "Starting $1"
}

function finish_log() {
  log "Finishing $1"
}


# Install neovim
if [[ ! -d /workspaces/neovim ]]; then
  start_log "Neovim installation"
  sudo apt-get install -y ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip curl
  git clone https://github.com/neovim/neovim ~/Projects/neovim
  cd ~/Projects/neovim
  make -j4
  sudo make install
  finish_log "Neovim installation"
  zsh -ci "pip install neovim"
fi

# Neovim config
if [[ ! -d /workspaces/neovim-config ]]; then
  start_log "Neovim Config"
  git clone https://github.com/mjacobus/neovim-config ~/Projects/neovim-config
  cd ~/Projects/neovim-config
  zsh -ci "./install.sh"
  start_log "Neovim Config"
fi

