#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup'
require 'dotfiles'

application_helper = Dotfiles::ApplicationHelper.new(ARGV.dup)
installer = Dotfiles::Installer.new([
  Dotfiles::Installers::Ag.new(application_helper)
])
installer.install(ARGV.dup)
