#!/usr/bin/env ruby
# frozen_string_literal: true

begin
  require 'colorized_string'
rescue LoadError
  puts "No colorized_string"
end

lib = File.expand_path('../lib', __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'dotfiles'

application_helper = Dotfiles::ApplicationHelper.new(ARGV.dup)
installer = Dotfiles::Installer.new([
  Dotfiles::Installers::Bash.new(application_helper),
  Dotfiles::Installers::Zshell.new(application_helper),
  Dotfiles::Installers::Ag.new(application_helper),
  Dotfiles::Installers::Ctags.new(application_helper),
  Dotfiles::Installers::Irb.new(application_helper),
  Dotfiles::Installers::Tmux.new(application_helper),
  Dotfiles::Installers::Git.new(application_helper),
  Dotfiles::Installers::Vim.new(application_helper),
  Dotfiles::Installers::Asdf.new(application_helper),
  Dotfiles::Installers::PhpUtils.new(application_helper)
])
installer.install(ARGV.dup)
